changelog:
  categories:
    - title: "🚀 Features"
      labels: ["feat"]
    - title: "🐛 Bug Fixes"
      labels: ["fix"]
    - title: "📖 Documentation"
      labels: ["docs"]
    - title: "⚙️ Maintenance"
      labels: ["chore", "ci", "refactor", "perf"]
    - title: "🔀 Other Changes"
      labels: ["*"]
